/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class RTPStreamProxy */

#ifndef _Included_RTPStreamProxy
#define _Included_RTPStreamProxy
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     RTPStreamProxy
 * Method:    nativeRTPStream
 * Signature: (IILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_RTPStreamProxy_nativeRTPStream
  (JNIEnv *, jclass, jint, jint, jstring);

/*
 * Class:     RTPStreamProxy
 * Method:    nativeSendFile
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_RTPStreamProxy_nativeSendFile
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     RTPStreamProxy
 * Method:    nativeReceive
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_RTPStreamProxy_nativeReceive
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     RTPStreamProxy
 * Method:    nativeSetRecord
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_RTPStreamProxy_nativeSetRecord
  (JNIEnv *, jobject, jint, jboolean);

/*
 * Class:     RTPStreamProxy
 * Method:    nativeIsRecording
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_RTPStreamProxy_nativeIsRecording
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
