/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mobeon_masp_stream_CCRTPSession */

#ifndef _Included_com_mobeon_masp_stream_CCRTPSession
#define _Included_com_mobeon_masp_stream_CCRTPSession
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mobeon_masp_stream_CCRTPSession
 * Method:    createInboundSession
 * Signature: (Lcom/mobeon/masp/stream/IMediaStream;)J
 */
JNIEXPORT jlong JNICALL Java_com_mobeon_masp_stream_CCRTPSession_createInboundSession
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_mobeon_masp_stream_CCRTPSession
 * Method:    createOutboundSession
 * Signature: (Lcom/mobeon/masp/stream/IMediaStream;)J
 */
JNIEXPORT jlong JNICALL Java_com_mobeon_masp_stream_CCRTPSession_createOutboundSession
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_mobeon_masp_stream_CCRTPSession
 * Method:    initConfiguration
 * Signature: (Lcom/mobeon/masp/stream/StreamConfiguration;)V
 */
JNIEXPORT void JNICALL Java_com_mobeon_masp_stream_CCRTPSession_initConfiguration
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_mobeon_masp_stream_CCRTPSession
 * Method:    updateConfiguration
 * Signature: (Lcom/mobeon/masp/stream/StreamConfiguration;)V
 */
JNIEXPORT void JNICALL Java_com_mobeon_masp_stream_CCRTPSession_updateConfiguration
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_mobeon_masp_stream_CCRTPSession
 * Method:    play
 * Signature: (ILcom/mobeon/masp/mediaobject/IMediaObject;IJJ)V
 */
JNIEXPORT void JNICALL Java_com_mobeon_masp_stream_CCRTPSession_play
  (JNIEnv *, jobject, jint, jobject, jint, jlong, jlong);

/*
 * Class:     com_mobeon_masp_stream_CCRTPSession
 * Method:    record
 * Signature: (Ljava/lang/Object;Lcom/mobeon/masp/mediaobject/IMediaObject;JLcom/mobeon/masp/mediaobject/IMediaObject;Lcom/mobeon/masp/stream/RecordingProperties;J)V
 */
JNIEXPORT void JNICALL Java_com_mobeon_masp_stream_CCRTPSession_record
  (JNIEnv *, jobject, jobject, jobject, jlong, jobject, jobject, jlong);

/*
 * Class:     com_mobeon_masp_stream_CCRTPSession
 * Method:    reNegotiatedSdp
 * Signature: (Lcom/mobeon/masp/stream/RTPPayload;J)V
 */
JNIEXPORT void JNICALL Java_com_mobeon_masp_stream_CCRTPSession_reNegotiatedSdp
  (JNIEnv *, jobject, jobject, jlong);

/*
 * Class:     com_mobeon_masp_stream_CCRTPSession
 * Method:    create
 * Signature: (Lcom/mobeon/masp/stream/StreamContentInfo;Lcom/mobeon/masp/stream/StackEventNotifier;IILjava/lang/String;ILjava/lang/String;IIJJ)V
 */
JNIEXPORT void JNICALL Java_com_mobeon_masp_stream_CCRTPSession_create__Lcom_mobeon_masp_stream_StreamContentInfo_2Lcom_mobeon_masp_stream_StackEventNotifier_2IILjava_lang_String_2ILjava_lang_String_2IIJJ
  (JNIEnv *, jobject, jobject, jobject, jint, jint, jstring, jint, jstring, jint, jint, jlong, jlong);

/*
 * Class:     com_mobeon_masp_stream_CCRTPSession
 * Method:    create
 * Signature: (Lcom/mobeon/masp/stream/StreamContentInfo;Lcom/mobeon/masp/stream/StackEventNotifier;IIJ)V
 */
JNIEXPORT void JNICALL Java_com_mobeon_masp_stream_CCRTPSession_create__Lcom_mobeon_masp_stream_StreamContentInfo_2Lcom_mobeon_masp_stream_StackEventNotifier_2IIJ
  (JNIEnv *, jobject, jobject, jobject, jint, jint, jlong);

/*
 * Class:     com_mobeon_masp_stream_CCRTPSession
 * Method:    delete
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_mobeon_masp_stream_CCRTPSession_delete
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_mobeon_masp_stream_CCRTPSession
 * Method:    stop
 * Signature: (Ljava/lang/Object;J)J
 */
JNIEXPORT jlong JNICALL Java_com_mobeon_masp_stream_CCRTPSession_stop
  (JNIEnv *, jobject, jobject, jlong);

/*
 * Class:     com_mobeon_masp_stream_CCRTPSession
 * Method:    setSkew
 * Signature: (IJJ)V
 */
JNIEXPORT void JNICALL Java_com_mobeon_masp_stream_CCRTPSession_setSkew
  (JNIEnv *, jobject, jint, jlong, jlong);

/*
 * Class:     com_mobeon_masp_stream_CCRTPSession
 * Method:    cancel
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_mobeon_masp_stream_CCRTPSession_cancel
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_mobeon_masp_stream_CCRTPSession
 * Method:    getCumulativePacketLost
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_mobeon_masp_stream_CCRTPSession_getCumulativePacketLost
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_mobeon_masp_stream_CCRTPSession
 * Method:    getFractionLost
 * Signature: (J)S
 */
JNIEXPORT jshort JNICALL Java_com_mobeon_masp_stream_CCRTPSession_getFractionLost
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_mobeon_masp_stream_CCRTPSession
 * Method:    send
 * Signature: ([Lcom/mobeon/masp/stream/ControlToken;IJ)V
 */
JNIEXPORT void JNICALL Java_com_mobeon_masp_stream_CCRTPSession_send
  (JNIEnv *, jobject, jobjectArray, jint, jlong);

/*
 * Class:     com_mobeon_masp_stream_CCRTPSession
 * Method:    join
 * Signature: (JJZZ)V
 */
JNIEXPORT void JNICALL Java_com_mobeon_masp_stream_CCRTPSession_join
  (JNIEnv *, jobject, jlong, jlong, jboolean, jboolean);

/*
 * Class:     com_mobeon_masp_stream_CCRTPSession
 * Method:    unjoin
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_mobeon_masp_stream_CCRTPSession_unjoin
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_mobeon_masp_stream_CCRTPSession
 * Method:    getSenderSSRC
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_mobeon_masp_stream_CCRTPSession_getSenderSSRC
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_mobeon_masp_stream_CCRTPSession
 * Method:    sendPictureFastUpdate
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_mobeon_masp_stream_CCRTPSession_sendPictureFastUpdate
  (JNIEnv *, jobject, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
