/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mobeon_masp_stream_jni_NativeStreamHandling */

#ifndef _Included_com_mobeon_masp_stream_jni_NativeStreamHandling
#define _Included_com_mobeon_masp_stream_jni_NativeStreamHandling
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mobeon_masp_stream_jni_NativeStreamHandling
 * Method:    initialize
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_mobeon_masp_stream_jni_NativeStreamHandling_initialize
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_mobeon_masp_stream_jni_NativeStreamHandling
 * Method:    getNativeCallback
 * Signature: (I[J)V
 */
JNIEXPORT void JNICALL Java_com_mobeon_masp_stream_jni_NativeStreamHandling_getNativeCallback
  (JNIEnv *, jclass, jint, jlongArray);

/*
 * Class:     com_mobeon_masp_stream_jni_NativeStreamHandling
 * Method:    postDummyCallback
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_mobeon_masp_stream_jni_NativeStreamHandling_postDummyCallback
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
