/*
 * Copyright (c) 2006 Mobeon AB. All Rights Reserved.
 */
package com.mobeon.masp.callmanager.callhandling.calleventlistener;

import com.mobeon.common.eventnotifier.Event;
import com.mobeon.masp.callmanager.Call;

/**
 * This class is an event containing the amount of dropped RTP packets for a call.
 * This event is generated by the call when it is disconnected and the inbound
 * stream is deleted. Before the stream is deleted, its amount of dropped
 * packets is collected and this event is sent to all call event listeners
 * registered in {@link com.mobeon.masp.callmanager.CMUtils}.
 * <p>
 * This class is immutable.
 * 
 * @author Malin Flodin
 */
public class DroppedPacketsEvent implements Event {
    private final Call call;
    private final int droppedPackets;

    public DroppedPacketsEvent(Call call, int droppedPackets) {
        this.call = call;
        this.droppedPackets = droppedPackets;
    }

    public Call getCall() {
        return call;
    }

    public int getDroppedPackets() {
        return droppedPackets;
    }

    public String toString() {
        return "DroppedPacketsEvent: <Call=" + call +
                ">, <Number of dropped packets = " +
                droppedPackets + ">";
    }
}
