#!/bin/sh
rm -f test.log >/dev/null 2>&1
LD_LIBRARY_PATH=/vobs/ipms/ntf/lib/:${LD_LIBRARY_PATH}
export LD_LIBRARY_PATH
if [ -w /data ] ; then
DATADIR=/data/$USER/build ;
else
DATADIR=$HOME/build
fi

JAVAHOME=/usr/local/jdk1.5.0_05
JAVA=$JAVAHOME/bin/java


$JAVA -classpath \
$DATADIR/`cleartool pwv -sho`/SOL_10/test-obj:\
$DATADIR/`cleartool pwv -sho`/SOL_10/obj:\
$DATADIR/`cleartool pwv -sho`/SOL_10/lib/ntf.jar:\
/proj/ipms/junit/junit3.8.1/junit.jar:/vobs/ipms/oem/Netscape/ldapsdk40/packages/ldapjdk.jar:\
/vobs/ipms/oem/Netscape/ldapsdk40/packages/ldapfilt.jar:\
/vobs/ipms/oem/Netscape/ldapsdk40/packages/ldapsp.jar:\
/vobs/ipms/ntf/bin/xmlParserAPIs.jar:\
/vobs/ipms/ntf/bin/xercesImpl.jar:\
/vobs/ipms/ntf/bin/foundation.jar:\
/vobs/ipms/ntf_oem/javamail-1.3/mail.jar:\
/vobs/ipms/ntf_oem/jaf-1.0.2/activation.jar:\
/vobs/ipms/ntf_oem/radius_api/radiusapi.jar:\
/vobs/ipms/ntf/bin/hsqldb.jar \
-DntfHome=/vobs/ipms/ntf/test/basictest/junit \
junit.swingui.TestRunner&


#-DconfigFile=/vobs/ipms/ntf/test/basictest/junit/notification.cfg \
