package com.mobeon.masp.execution_engine.util;

/**
 * Created by IntelliJ IDEA.
 * User: QMIAN
 * Date: 2007-jan-31
 * Time: 19:15:40
 * To change this template use File | Settings | File Templates.
 */
public enum TestEvent {
    DISCONNECTER_DISCONNECT,
    WAITSET_REQUIRED,
    APPLICATION_COMPILER_GENERATEOPS,
    APPLICATION_COMPILER_PATH,
    ENGINE_STACKSIZE,
    ENGINE_TRACE,
    CONNECTION_CONFIG_ACCEPT_TIMEOUT,
    CONNECTION_CONFIG_CALLMGR_WAIT,
    CONNECTION_CONFIG_CREATECALL_ADDITIONAL,
    CREATE_PLAYABLE_OBJECT_TM_P,
    PROMPT_QUEUE_PLAY,
    NOINPUT_STARTING,
    NOINPUT_DISCARDED,
    PROPERTYSTACK_PUT_PROPERTY,
    PROPERTYSTACK_PUT_PROPERTY_OLD,
    SCOPE_COMPILATION_FAILED,
    SCOPE_EVALUATION_FAILED,
    ACCEPT,
    PLAY_STARTED,
    RECOGNIZER_PREPARE,
    RECOGNIZER_RECOGNIZE,
    TRANSFER_INITIATED,
    RECORD_STARTED,
    RECORD_STARTING,
    VXML_MODULE_STARTED,
    CCXML_MODULE_STARTED,
    EVENT_NOINPUT_SENT,
    FINAL_PROCESSING_STATE,
    ECMA_VAR,
    CONFIG_ENGINE_POOLSIZE,
    ENGINE_CREATED,
    ENGINE_REUSED,
    ENGINE_RELEASED
}
