/*
 *
 * Copyright (C) 1992-2009 by SNMP Research, Incorporated.
 *
 * This software is furnished under a license and may be used and copied
 * only in accordance with the terms of such license and with the
 * inclusion of the above copyright notice. This software or any other
 * copies thereof may not be provided or otherwise made available to any
 * other person. No title to and ownership of the software is hereby
 * transferred.
 *
 * The information in this software is subject to change without notice
 * and should not be construed as a commitment by SNMP Research, Incorporated.
 *
 * Restricted Rights Legend:
 *  Use, duplication, or disclosure by the Government is subject to
 *  restrictions as set forth in subparagraph (c)(1)(ii) of the Rights
 *  in Technical Data and Computer Software clause at DFARS 252.227-7013;
 *  subparagraphs (c)(4) and (d) of the Commercial Computer
 *  Software-Restricted Rights Clause, FAR 52.227-19; and in similar
 *  clauses in the NASA FAR Supplement and other corresponding
 *  governmental regulations.
 *
 */

/*
 *                PROPRIETARY NOTICE
 *
 * This software is an unpublished work subject to a confidentiality agreement
 * and is protected by copyright and trade secret law.  Unauthorized copying,
 * redistribution or other use of this work is prohibited.
 *
 * The above notice of copyright on this source code product does not indicate
 * any actual or intended publication of such source code.
 */


/*
 * Arguments used to create this file:
 * -o ntf -agent -traps 
 */

/*
 * automatically generated by the mib compiler -- do not edit
 */

#ifndef SR_NTFDEFS_H
#define SR_NTFDEFS_H


#ifdef __cplusplus
extern "C" {
#endif

/* enumerated values for ntfOperationalState */
#define D_ntfOperationalState_enabled  1
#define D_ntfOperationalState_disabled 2

/* enumerated values for ntfAdministrativeState */
#define D_ntfAdministrativeState_unlocked 1
#define D_ntfAdministrativeState_locked 2
#define D_ntfAdministrativeState_shutdown 3

/* enumerated values for ntfLoadConfig */
#define D_ntfLoadConfig_active         1
#define D_ntfLoadConfig_inactive       2

/* enumerated values for ntfLogLevel */
#define D_ntfLogLevel_off              0
#define D_ntfLogLevel_error            1
#define D_ntfLogLevel_warning          2
#define D_ntfLogLevel_verbose          3

/* enumerated values for ntfMailboxPollerStatus */
#define D_ntfMailboxPollerStatus_active 1
#define D_ntfMailboxPollerStatus_inactive 2

/* enumerated values for alarmStatus */
#define D_alarmStatus_raised           1
#define D_alarmStatus_cleared          2
#define D_alarmStatus_notAvailable     3

/* enumerated values for ntfConsumedServiceStatus */
#define D_ntfConsumedServiceStatus_up  1
#define D_ntfConsumedServiceStatus_down 2
#define D_ntfConsumedServiceStatus_impaired 3

/* enumerated values for ntfConsumedServiceInstancesStatus */
#define D_ntfConsumedServiceInstancesStatus_up 1
#define D_ntfConsumedServiceInstancesStatus_down 2
#define D_ntfConsumedServiceInstancesStatus_impaired 3


#ifdef __cplusplus
}
#endif

/* DO NOT PUT ANYTHING AFTER THIS #endif */
#endif /* SR_NTFDEFS_H */
