/*
 *
 * Copyright (C) 1992-2009 by SNMP Research, Incorporated.
 *
 * This software is furnished under a license and may be used and copied
 * only in accordance with the terms of such license and with the
 * inclusion of the above copyright notice. This software or any other
 * copies thereof may not be provided or otherwise made available to any
 * other person. No title to and ownership of the software is hereby
 * transferred.
 *
 * The information in this software is subject to change without notice
 * and should not be construed as a commitment by SNMP Research, Incorporated.
 *
 * Restricted Rights Legend:
 *  Use, duplication, or disclosure by the Government is subject to
 *  restrictions as set forth in subparagraph (c)(1)(ii) of the Rights
 *  in Technical Data and Computer Software clause at DFARS 252.227-7013;
 *  subparagraphs (c)(4) and (d) of the Commercial Computer
 *  Software-Restricted Rights Clause, FAR 52.227-19; and in similar
 *  clauses in the NASA FAR Supplement and other corresponding
 *  governmental regulations.
 *
 */

/*
 *                PROPRIETARY NOTICE
 *
 * This software is an unpublished work subject to a confidentiality agreement
 * and is protected by copyright and trade secret law.  Unauthorized copying,
 * redistribution or other use of this work is prohibited.
 *
 * The above notice of copyright on this source code product does not indicate
 * any actual or intended publication of such source code.
 */


/*
 * Arguments used to create this file:
 * -o ntf -agent -traps 
 */

/*
 * If your implementation does NOT support a MIB variable, add a line in
 * the undefs.h file containing #undef I_that-variable-name.  For example,
 * if you do not support the sysDescr variable in the system family
 * add a line:
 *
 * #undef I_sysDescr
 *
 *
 */


/*
 * automatically generated by the mib compiler -- do not edit
 */

#ifndef SR_NTFSUPP_H
#define SR_NTFSUPP_H


#ifdef __cplusplus
extern "C" {
#endif

#define I_ntfName                                           0
#define I_ntfVersion                                        1
#define I_ntfOperationalState                               2
#define I_ntfAdministrativeState                            3
#define I_ntfInstallDate                                    4
#define I_ntfCurrentUpTime                                  5
#define I_ntfAccumulatedUpTime                              6
#define I_ntfNotifInQueue                                   7
#define I_ntfNotifForRetry                                  8
#define I_ntfInternalQueues                                 9
#define I_ntfLoadConfig                                     10
#define I_ntfLogLevel                                       11
#define I_ntfMailboxPollerStatus                            12
#define I_ntfObjects_max                                    12

#define I_alarmIndex                                        0
#define I_alarmId                                           1
#define I_alarmStatus                                       2
#define I_commonAlarmsEntry_max                             2

#define I_ntfConsumedServiceIndex                           0
#define I_ntfConsumedServiceName                            1
#define I_ntfConsumedServiceStatus                          2
#define I_ntfConsumedServiceTime                            3
#define I_ntfConsumedServiceNumSuccess                      4
#define I_ntfConsumedServiceNumFailures                     5
#define I_ntfConsumedServiceEntry_max                       5

#define I_ntfConsumedServiceInstancesIndex                  0
#define I_ntfConsumedServiceInstancesName                   1
#define I_ntfConsumedServiceInstancesStatus                 2
#define I_ntfConsumedServiceInstancesHostName               3
#define I_ntfConsumedServiceInstancesPort                   4
#define I_ntfConsumedServiceInstancesZone                   5
#define I_ntfConsumedServiceInstancesEntryIndex_ntfConsumedServiceIndex 6
#define I_ntfConsumedServiceInstancesEntry_max              6

#include "undefs.h"


#ifdef __cplusplus
}
#endif

/* DO NOT PUT ANYTHING AFTER THIS #endif */
#endif /* SR_NTFSUPP_H */
