#!/bin/sh
# Sun Cluster Data Services Builder template version 1.0

RT_NAME=ntf
RT_VENDOR=LMEA
RT_FULLNAME=$RT_VENDOR$RT_NAME

RTRDIR=${PKG_INSTALL_ROOT}/usr/cluster/lib/rgm/rtreg
# Remove the link from the RT repository directory

rm -f $RTRDIR/$RT_VENDOR.$RT_NAME

exit $?
