#!/bin/sh

DATE=`date +%Y_%m_%d_%H%M`
MAS_INSTANCE_NAME=$REGISTERED_NAME"@"$MAS_HOST


# Check if the patch can be removed
####################################

# Necessary?



# Set PATCH_LOGFILE to the wanted component uninstall log file
###############################################################

PATCH_LOGFILE="$BASEDIR/../logs/mas/$MAS_INSTANCE_NAME.$DATE.uninstallog"


# Export to pkgparam
#####################
cat >>$1 <<EOF
PATCH_LOGFILE=$PATCH_LOGFILE
EOF
