# Makefile.in generated automatically by automake 1.4-p6 from Makefile.am

# Copyright (C) 1994, 1995-8, 1999, 2001 Free Software Foundation, Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.

# Copyright (C) 1999-2005 Open Source Telecom Corporation.
#
# This file is free software; as a special exception the author gives
# unlimited permission to copy and/or distribute it, with or without
# modifications, as long as this notice is preserved.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY, to the extent permitted by law; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.


SHELL = /bin/sh

srcdir = .
top_srcdir = ..

prefix = /usr/local
exec_prefix = ${prefix}

bindir = ${exec_prefix}/bin
sbindir = ${exec_prefix}/sbin
libexecdir = ${exec_prefix}/libexec
datadir = ${prefix}/share
sysconfdir = ${prefix}/etc
sharedstatedir = ${prefix}/com
localstatedir = ${prefix}/var
libdir = ${exec_prefix}/lib
infodir = ${prefix}/info
mandir = ${prefix}/man
includedir = ${prefix}/include
oldincludedir = /usr/include

DESTDIR =

pkgdatadir = $(datadir)/commoncpp2
pkglibdir = $(libdir)/commoncpp2
pkgincludedir = $(includedir)/commoncpp2

top_builddir = ..

ACLOCAL = /home/mikael/eIII/mas/stream/nativestreamhandling/3pp/commoncpp2-1.3.22/autoconf/missing aclocal-1.4
AUTOCONF = /home/mikael/eIII/mas/stream/nativestreamhandling/3pp/commoncpp2-1.3.22/autoconf/missing autoconf
AUTOMAKE = /home/mikael/eIII/mas/stream/nativestreamhandling/3pp/commoncpp2-1.3.22/autoconf/missing automake-1.4
AUTOHEADER = /home/mikael/eIII/mas/stream/nativestreamhandling/3pp/commoncpp2-1.3.22/autoconf/missing autoheader

INSTALL = /usr/bin/install -c
INSTALL_PROGRAM = ${INSTALL} $(AM_INSTALL_PROGRAM_FLAGS)
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_SCRIPT = ${INSTALL}
transform = s,x,x,

NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
build_alias = 
build_triplet = x86_64-unknown-linux-gnu
host_alias = 
host_triplet = x86_64-unknown-linux-gnu
target_alias = 
target_triplet = x86_64-unknown-linux-gnu
AR = ar
AS = @AS@
BASE_LIB = 
CC = gcc
CCXX_DIR = $(top_srcdir)/include
COMMON_FLAGS = -D_GNU_SOURCE
CPP = gcc -E
CPPUNIT_LIBS =  
CXX = g++
CXXCPP = g++ -E
DLLTOOL = @DLLTOOL@
DOXYGEN = no
DYN_LOADER = -ldl
ECHO = echo
EGREP = grep -E
EXEEXT = 
F77 = 
FTPDIR = 
GCJ = @GCJ@
GCJFLAGS = @GCJFLAGS@
GETOPT_LIBS = 
HAVE_LIB = @HAVE_LIB@
KDOC_DIR = $(top_srcdir)/doc
LIB = @LIB@
LIBGETOPTOBJS = 
LIBTOOL = $(SHELL) $(top_builddir)/libtool
LN_S = ln -s
LTLIB = @LTLIB@
LT_ = @LT_@
LT_MAJOR = 1
LT_MINOR = 18
LT_RELEASE = 1.3
LT_SUBVER = 1.18
MAINT = #
MAKEINFO = /home/mikael/eIII/mas/stream/nativestreamhandling/3pp/commoncpp2-1.3.22/autoconf/missing makeinfo
MODULE_FLAGS = -module -shared
OBJDUMP = @OBJDUMP@
OBJEXT = o
PACKAGE = commoncpp2
PTHREAD_CC = 
RANLIB = ranlib
RC = @RC@
SHARED_FLAGS = 
SOCKET_LIBS = 
STAGE2 = 
STRIP = strip
THREAD_FLAGS = 
THREAD_LIBS =   -lrt -pthread
VERSION = 1.3.22
WARN_FLAGS = -pedantic -Wall
WINVERSION = 1,3,22,0
XML2_CONFIG = no
XML_CONFIG = no
XML_FLAGS = 
XML_LIBS = 
ZSTREAM_LIBS = 
ccincludedir = ${includedir}/cc++2
datadir = ${prefix}/share
incprefix = 
infodir = ${prefix}/info
localstatedir = ${prefix}/var
mandir = ${prefix}/man
ost_cv_dynloader = yes
prefix = /usr/local
sysconfdir = ${prefix}/etc
thrprefix = /usr/include

MAINTAINERCLEANFILES = Makefile.in Makefile

EXTRA_DIST = README dotests.sh test.sh output.txt vc6.mak Makefile.bcc
AM_CXXFLAGS = $(THREAD_FLAGS) -pedantic -Wall
INCLUDES = -I$(top_srcdir)/include
LDADD = ../src/libccgnu2.la $(THREAD_LIBS) $(DYN_LOADER)
Z_LIBS = -lz
#TEST_SUITE = ccxx_tests
TEST_SUITE = 

noinst_PROGRAMS = $(TEST_SUITE) 	bug1 bug2 thread1 thread2 thread3 digest tcpstr1 url1 forever


noinst_HEADERS = SampleObject.h SampleSubObject.h Test_Date.h Test_Digest.h         Test_Engine.h Test_SHATumbler.h Test_TCPStream.h Test_URLString.h


#ccxx_tests_SOURCES = ccxx_tests.cpp SampleObject.cpp SampleSubObject.cpp 	Test_Date.cpp Test_Engine.cpp Test_TCPStream.cpp Test_URLString.cpp
# Test_Digest.cpp
#ccxx_tests_LDADD = ../src/libccext2.la $(XML_LIBS) $(Z_LIBS) $(LDADD) 	$(CPPUNIT_LIBS)

bug1_SOURCES = bug1.cpp

bug2_SOURCES = bug2.cpp

forever_SOURCES = forever.cpp

digest_SOURCES = digest.cpp
digest_LDADD = ../src/libccext2.la $(XML_LIBS) $(Z_LIBS) $(LDADD)

thread1_SOURCES = thread1.cpp

thread2_SOURCES = thread2.cpp

thread3_SOURCES = thread3.cpp

tcpstr1_SOURCES = tcpstr1.cpp

url1_SOURCES = url1.cpp
url1_LDADD = ../src/libccext2.la $(XML_LIBS) $(Z_LIBS) $(LDADD)
mkinstalldirs = $(SHELL) $(top_srcdir)/autoconf/mkinstalldirs
CONFIG_HEADER = ../include/config.h
CONFIG_CLEAN_FILES = 
noinst_PROGRAMS =  bug1$(EXEEXT) bug2$(EXEEXT) \
thread1$(EXEEXT) thread2$(EXEEXT) \
thread3$(EXEEXT) digest$(EXEEXT) \
tcpstr1$(EXEEXT) url1$(EXEEXT) \
forever$(EXEEXT)
#noinst_PROGRAMS =  ccxx_tests$(EXEEXT) \
#bug1$(EXEEXT) bug2$(EXEEXT) thread1$(EXEEXT) \
#thread2$(EXEEXT) thread3$(EXEEXT) \
#digest$(EXEEXT) tcpstr1$(EXEEXT) url1$(EXEEXT) \
#forever$(EXEEXT)
PROGRAMS =  $(noinst_PROGRAMS)


DEFS = -DHAVE_CONFIG_H -I. -I$(srcdir) -I../include
CPPFLAGS = 
LDFLAGS = 
LIBS =  -L/lib
#ccxx_tests_OBJECTS =  ccxx_tests.$(OBJEXT) \
#SampleObject.$(OBJEXT) \
#SampleSubObject.$(OBJEXT) Test_Date.$(OBJEXT) \
#Test_Engine.$(OBJEXT) Test_TCPStream.$(OBJEXT) \
#Test_URLString.$(OBJEXT)
#ccxx_tests_DEPENDENCIES =  ../src/libccext2.la \
#../src/libccgnu2.la
ccxx_tests_LDFLAGS = 
bug1_OBJECTS =  bug1.$(OBJEXT)
bug1_LDADD = $(LDADD)
bug1_DEPENDENCIES =  ../src/libccgnu2.la
bug1_LDFLAGS = 
bug2_OBJECTS =  bug2.$(OBJEXT)
bug2_LDADD = $(LDADD)
bug2_DEPENDENCIES =  ../src/libccgnu2.la
bug2_LDFLAGS = 
thread1_OBJECTS =  thread1.$(OBJEXT)
thread1_LDADD = $(LDADD)
thread1_DEPENDENCIES =  ../src/libccgnu2.la
thread1_LDFLAGS = 
thread2_OBJECTS =  thread2.$(OBJEXT)
thread2_LDADD = $(LDADD)
thread2_DEPENDENCIES =  ../src/libccgnu2.la
thread2_LDFLAGS = 
thread3_OBJECTS =  thread3.$(OBJEXT)
thread3_LDADD = $(LDADD)
thread3_DEPENDENCIES =  ../src/libccgnu2.la
thread3_LDFLAGS = 
digest_OBJECTS =  digest.$(OBJEXT)
digest_DEPENDENCIES =  ../src/libccext2.la ../src/libccgnu2.la
digest_LDFLAGS = 
tcpstr1_OBJECTS =  tcpstr1.$(OBJEXT)
tcpstr1_LDADD = $(LDADD)
tcpstr1_DEPENDENCIES =  ../src/libccgnu2.la
tcpstr1_LDFLAGS = 
url1_OBJECTS =  url1.$(OBJEXT)
url1_DEPENDENCIES =  ../src/libccext2.la ../src/libccgnu2.la
url1_LDFLAGS = 
forever_OBJECTS =  forever.$(OBJEXT)
forever_LDADD = $(LDADD)
forever_DEPENDENCIES =  ../src/libccgnu2.la
forever_LDFLAGS = 
CXXFLAGS =  -g -O2
CXXCOMPILE = $(CXX) $(DEFS) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS)
LTCXXCOMPILE = $(LIBTOOL) --mode=compile $(CXX) $(DEFS) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS)
CXXLD = $(CXX)
CXXLINK = $(LIBTOOL) --mode=link $(CXXLD) $(AM_CXXFLAGS) $(CXXFLAGS) $(LDFLAGS) -o $@
HEADERS =  $(noinst_HEADERS)

DIST_COMMON =  README Makefile.am Makefile.in


DISTFILES = $(DIST_COMMON) $(SOURCES) $(HEADERS) $(TEXINFOS) $(EXTRA_DIST)

TAR = tar
GZIP_ENV = --best
SOURCES = $(ccxx_tests_SOURCES) $(bug1_SOURCES) $(bug2_SOURCES) $(thread1_SOURCES) $(thread2_SOURCES) $(thread3_SOURCES) $(digest_SOURCES) $(tcpstr1_SOURCES) $(url1_SOURCES) $(forever_SOURCES)
OBJECTS = $(ccxx_tests_OBJECTS) $(bug1_OBJECTS) $(bug2_OBJECTS) $(thread1_OBJECTS) $(thread2_OBJECTS) $(thread3_OBJECTS) $(digest_OBJECTS) $(tcpstr1_OBJECTS) $(url1_OBJECTS) $(forever_OBJECTS)

all: all-redirect
.SUFFIXES:
.SUFFIXES: .S .c .cpp .lo .o .obj .s
$(srcdir)/Makefile.in: # Makefile.am $(top_srcdir)/configure.ac $(ACLOCAL_M4) 
	cd $(top_srcdir) && $(AUTOMAKE) --gnu --include-deps tests/Makefile

Makefile: $(srcdir)/Makefile.in  $(top_builddir)/config.status
	cd $(top_builddir) \
	  && CONFIG_FILES=$(subdir)/$@ CONFIG_HEADERS= $(SHELL) ./config.status


mostlyclean-noinstPROGRAMS:

clean-noinstPROGRAMS:
	-test -z "$(noinst_PROGRAMS)" || rm -f $(noinst_PROGRAMS)

distclean-noinstPROGRAMS:

maintainer-clean-noinstPROGRAMS:

.c.o:
	$(COMPILE) -c $<

# FIXME: We should only use cygpath when building on Windows,
# and only if it is available.
.c.obj:
	$(COMPILE) -c `cygpath -w $<`

.s.o:
	$(COMPILE) -c $<

.S.o:
	$(COMPILE) -c $<

mostlyclean-compile:
	-rm -f *.o core *.core
	-rm -f *.$(OBJEXT)

clean-compile:

distclean-compile:
	-rm -f *.tab.c

maintainer-clean-compile:

.c.lo:
	$(LIBTOOL) --mode=compile $(COMPILE) -c $<

.s.lo:
	$(LIBTOOL) --mode=compile $(COMPILE) -c $<

.S.lo:
	$(LIBTOOL) --mode=compile $(COMPILE) -c $<

mostlyclean-libtool:
	-rm -f *.lo

clean-libtool:
	-rm -rf .libs _libs

distclean-libtool:

maintainer-clean-libtool:

ccxx_tests$(EXEEXT): $(ccxx_tests_OBJECTS) $(ccxx_tests_DEPENDENCIES)
	@rm -f ccxx_tests$(EXEEXT)
	$(CXXLINK) $(ccxx_tests_LDFLAGS) $(ccxx_tests_OBJECTS) $(ccxx_tests_LDADD) $(LIBS)

bug1$(EXEEXT): $(bug1_OBJECTS) $(bug1_DEPENDENCIES)
	@rm -f bug1$(EXEEXT)
	$(CXXLINK) $(bug1_LDFLAGS) $(bug1_OBJECTS) $(bug1_LDADD) $(LIBS)

bug2$(EXEEXT): $(bug2_OBJECTS) $(bug2_DEPENDENCIES)
	@rm -f bug2$(EXEEXT)
	$(CXXLINK) $(bug2_LDFLAGS) $(bug2_OBJECTS) $(bug2_LDADD) $(LIBS)

thread1$(EXEEXT): $(thread1_OBJECTS) $(thread1_DEPENDENCIES)
	@rm -f thread1$(EXEEXT)
	$(CXXLINK) $(thread1_LDFLAGS) $(thread1_OBJECTS) $(thread1_LDADD) $(LIBS)

thread2$(EXEEXT): $(thread2_OBJECTS) $(thread2_DEPENDENCIES)
	@rm -f thread2$(EXEEXT)
	$(CXXLINK) $(thread2_LDFLAGS) $(thread2_OBJECTS) $(thread2_LDADD) $(LIBS)

thread3$(EXEEXT): $(thread3_OBJECTS) $(thread3_DEPENDENCIES)
	@rm -f thread3$(EXEEXT)
	$(CXXLINK) $(thread3_LDFLAGS) $(thread3_OBJECTS) $(thread3_LDADD) $(LIBS)

digest$(EXEEXT): $(digest_OBJECTS) $(digest_DEPENDENCIES)
	@rm -f digest$(EXEEXT)
	$(CXXLINK) $(digest_LDFLAGS) $(digest_OBJECTS) $(digest_LDADD) $(LIBS)

tcpstr1$(EXEEXT): $(tcpstr1_OBJECTS) $(tcpstr1_DEPENDENCIES)
	@rm -f tcpstr1$(EXEEXT)
	$(CXXLINK) $(tcpstr1_LDFLAGS) $(tcpstr1_OBJECTS) $(tcpstr1_LDADD) $(LIBS)

url1$(EXEEXT): $(url1_OBJECTS) $(url1_DEPENDENCIES)
	@rm -f url1$(EXEEXT)
	$(CXXLINK) $(url1_LDFLAGS) $(url1_OBJECTS) $(url1_LDADD) $(LIBS)

forever$(EXEEXT): $(forever_OBJECTS) $(forever_DEPENDENCIES)
	@rm -f forever$(EXEEXT)
	$(CXXLINK) $(forever_LDFLAGS) $(forever_OBJECTS) $(forever_LDADD) $(LIBS)
.cpp.o:
	$(CXXCOMPILE) -c $<
.cpp.obj:
	$(CXXCOMPILE) -c `cygpath -w $<`
.cpp.lo:
	$(LTCXXCOMPILE) -c $<

tags: TAGS

ID: $(HEADERS) $(SOURCES) $(LISP)
	list='$(SOURCES) $(HEADERS)'; \
	unique=`for i in $$list; do echo $$i; done | \
	  awk '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	here=`pwd` && cd $(srcdir) \
	  && mkid -f$$here/ID $$unique $(LISP)

TAGS:  $(HEADERS) $(SOURCES)  $(TAGS_DEPENDENCIES) $(LISP)
	tags=; \
	here=`pwd`; \
	list='$(SOURCES) $(HEADERS)'; \
	unique=`for i in $$list; do echo $$i; done | \
	  awk '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	test -z "$(ETAGS_ARGS)$$unique$(LISP)$$tags" \
	  || (cd $(srcdir) && etags -o $$here/TAGS $(ETAGS_ARGS) $$tags  $$unique $(LISP))

mostlyclean-tags:

clean-tags:

distclean-tags:
	-rm -f TAGS ID

maintainer-clean-tags:

distdir = $(top_builddir)/$(PACKAGE)-$(VERSION)/$(subdir)

subdir = tests

distdir: $(DISTFILES)
	@for file in $(DISTFILES); do \
	  d=$(srcdir); \
	  if test -d $$d/$$file; then \
	    cp -pr $$d/$$file $(distdir)/$$file; \
	  else \
	    test -f $(distdir)/$$file \
	    || ln $$d/$$file $(distdir)/$$file 2> /dev/null \
	    || cp -p $$d/$$file $(distdir)/$$file || :; \
	  fi; \
	done

info-am:
info: info-am
dvi-am:
dvi: dvi-am
check-am: all-am
check: check-am
installcheck-am:
installcheck: installcheck-am
install-exec-am:
install-exec: install-exec-am

install-data-am:
install-data: install-data-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am
install: install-am
uninstall-am:
uninstall: uninstall-am
all-am: Makefile $(PROGRAMS) $(HEADERS)
all-redirect: all-am
install-strip:
	$(MAKE) $(AM_MAKEFLAGS) AM_INSTALL_PROGRAM_FLAGS=-s install
installdirs:


mostlyclean-generic:

clean-generic:

distclean-generic:
	-rm -f Makefile $(CONFIG_CLEAN_FILES)
	-rm -f config.cache config.log stamp-h stamp-h[0-9]*

maintainer-clean-generic:
	-test -z "$(MAINTAINERCLEANFILES)" || rm -f $(MAINTAINERCLEANFILES)
mostlyclean-am:  mostlyclean-noinstPROGRAMS mostlyclean-compile \
		mostlyclean-libtool mostlyclean-tags \
		mostlyclean-generic

mostlyclean: mostlyclean-am

clean-am:  clean-noinstPROGRAMS clean-compile clean-libtool clean-tags \
		clean-generic mostlyclean-am

clean: clean-am

distclean-am:  distclean-noinstPROGRAMS distclean-compile \
		distclean-libtool distclean-tags distclean-generic \
		clean-am
	-rm -f libtool

distclean: distclean-am

maintainer-clean-am:  maintainer-clean-noinstPROGRAMS \
		maintainer-clean-compile maintainer-clean-libtool \
		maintainer-clean-tags maintainer-clean-generic \
		distclean-am
	@echo "This command is intended for maintainers to use;"
	@echo "it deletes files that may require special tools to rebuild."

maintainer-clean: maintainer-clean-am

.PHONY: mostlyclean-noinstPROGRAMS distclean-noinstPROGRAMS \
clean-noinstPROGRAMS maintainer-clean-noinstPROGRAMS \
mostlyclean-compile distclean-compile clean-compile \
maintainer-clean-compile mostlyclean-libtool distclean-libtool \
clean-libtool maintainer-clean-libtool tags mostlyclean-tags \
distclean-tags clean-tags maintainer-clean-tags distdir info-am info \
dvi-am dvi check check-am installcheck-am installcheck install-exec-am \
install-exec install-data-am install-data install-am install \
uninstall-am uninstall all-redirect all-am all installdirs \
mostlyclean-generic distclean-generic clean-generic \
maintainer-clean-generic clean mostlyclean distclean maintainer-clean


# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
